### PR TITLE
weka: disable cachesize collection (hangs on AMD genoa, and unused)

### PR DESCRIPTION
**Pull request by gdamore**

### CODE REVIEW

**Comment by gdamore** [comment]
The code in question is entirely misguided, x86-only, and basically useless.  It's brittle and broken.  

My strong vote would be to remove it from upstream entirely.  But for now we can do this.  (The breakage looks like an infinite loop in core.cpuid.getcacheinfoCPUID2 - see WEKAPP-404256 for details

**Comment by gdamore** [comment]
@ari-weka here's the change in context in D runtime.  This file is the same for LDC 1.24 and LDC 1.30.

**Review by ljmf00-wekaio — APPROVED** [review]
Cool. We should also fix this on LDC, as after a few LDC versions, druntime is now backed in the LDC repo itself (no longer a separate repo).

**Comment by gdamore** [comment]
@ljmf00-wekaio and @JohanEngelen can you guys fix the LDC repo then?  I can push these forward for 1.30 in the meantime.

**Comment by gdamore** [comment]
I'm merging this by hand.  @JohanEngelen I hope you can look afterwards.

**Comment by gdamore** [comment]
Closing this, apparently github is confused.  I merged it manually.

**Pull request closed without merging**
